services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autopan-app
    ports:
      - "3000:3000"
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    stdin_open: true
    tty: true
